production:
  sessions:
    default:
      uri:  <%= ENV["DATABASE_URL"] %> #mongodb://zlfera:01300727zz@oceanic.mongohq.com:10091/zlfera

        
development:
  sessions:
    default:
      uri:  <%= ENV["DATABASE_URL"] %> #mongodb://zlfera:01300727zz@oceanic.mongohq.com:10091/zlfera