production:
  sessions:
    default:
      uri: mongodb://zlfera:01300727zz@oceanic.mongohq.com:10091/zlfera #<%= ENV["DATABASE_URL"] %>
      options: 
        consistency: :strong
        max_retries: 30
        retry_interval: 1
        timeout: 15
        
development:
  sessions:
    default:
      uri: mongodb://zlfera:01300727zz@oceanic.mongohq.com:10091/zlfera #<%= ENV["DATABASE_URL"] %>
      options: 
        consistency: :strong
        max_retries: 30
        retry_interval: 1
        timeout: 15