production:
  sessions:
    default:
      uri: mongodb://zlfera:01300727zz@oceanic.mongohq.com:10091/zlfera #<%= ENV["DATABASE_URL"] %>

        
development:
  sessions:
    default:
      uri: mongodb://zlfera:01300727zz@oceanic.mongohq.com:10091/zlfera #<%= ENV["DATABASE_URL"] %>